### ISSUE TITLE
Upgrade to /Messages resource URI

### ISSUE THREAD

**Issue by jesteves** [mbeijen/SMS-Send-Twilio#5]
You may want to consider this:  https://support.twilio.com/hc/en-us/articles/223181028-Switching-from-SMS-Messages-resource-URI-to-Messages-resource-URI-

It seems to reduce to simply update only [one line of code](https://github.com/mbeijen/SMS-Send-Twilio/blob/master/lib/SMS/Send/Twilio.pm#L107).

> _For such a minimal change I'm neglecting doing a pull request right now..._

In Twilio's console the change is evident in that requests using [the deprecated] `SMS/Messages` have no "Delivery Steps", while the ones using `/Messages` have.  It may be not a critical feature, but it is certainly a useful one.

**Comment by GoodMirek** [comment]
Another advantage of new resource is ability to split message into multiple segments, i.e. send messages longer than 160 chars.

**Comment by jesteves** [comment]
@mbeijen Thanks for [this](https://github.com/mbeijen/SMS-Send-Twilio/blob/5a3e1ebe0f8d7eeb8d3bde4a0b44507dcde1be58/Changes#L7).  Glad to collaborate.  :+1:

**Comment by mbeijen** [comment]
Sure, no problem! It's on CPAN now, version 0.20.
